### ISSUE TITLE
setState(...): Can only update a mounted...

### ISSUE THREAD

**Issue by Remownz** [sergeybekrin/react-with-async-fonts#22]
I some cases a component is unmounted before font loading is finished. I think you need a componentWillUnmount method which resolves font loading immediately otherwise you get the warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the WithAsyncFontsHoC component. see https://github.com/sergeybekrin/react-with-async-fonts/blob/b8d8b8c6a57ff6dc34e6e9baa89ee863df11e83d/src/index.ts#L68

**Comment by sbekrin** [comment]
Hey @Remownz, thanks for reporting this!

I definitely see that issue, will fix that soon.

**Comment by sbekrin** [comment]
@Remownz this bug should be fixed with `3.0.2`. Feel free to reopen this issue if that won't work for you.

**Comment by Remownz** [comment]
hmm, you have added a dependency (make-cancelable) which isn't working with CRAs build task:
If i build my app i get the message:

> Failed to minify the code from this file: 
> 
>  	./node_modules/make-cancelable/index.js:1

**Comment by sbekrin** [comment]
@Remownz I believe CRA uses UglifyJS which does't support ES6. I've created #25 since it's separate issue now.
