### ISSUE TITLE
Republish types?

### ISSUE THREAD

**Issue by jimthedev** [sergeybekrin/react-with-async-fonts#26]
It looks like the types in ./lib/index.d.ts don't match up with the ones in https://github.com/sergeybekrin/react-with-async-fonts/blob/master/with-async-fonts.d.ts

I'm not quite sure if they are supposed to match but vscode seems to be sad when using this as a lib.

**Comment by sbekrin** [comment]
Hey @jimthedev, thanks for reporting this! 

Since typings are generated by TS, it might be they are out-of-sync (or just missing .d.ts from sources). I'll take a look once I have time 👍

**Comment by jimthedev** [comment]
Any chance that while you work on this you could remove the existing "types" key in package.json? It is making it tricky to override the types for this module that seem not to be working. If not, no worries. 👍

**Comment by sbekrin** [comment]
@jimthedev ok I've tried couple of things and it appears TS can't generate typings in such format as we need. I've pointed `typings` field now to source code, so it should resolves typings in `3.1.0`. Please check if that works for you.

**Comment by jimthedev** [comment]
Unfortunately this doesn't seem to work for me. It is ok for now since there are two types that need PRs landed before we can make any progress on this. Until then people will just have to patch their types locally:

FontObserver needs to allow null for load()'s first param:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/21038

Enzyme needs to allow arrays for containsMatchingElement:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/21046

Once those are landed then then I can put in the PR from my fork that changes the way that the types are generated. I actually have it all stubbed out locally and working with tests and builds compiling.

**Comment by sbekrin** [comment]
@jimthedev sounds great, thanks!

**Comment by jimthedev** [comment]
While we wait I have published http://npm.im/jimthedev-react-with-async-fonts which has the types from the above two PRs hard coded into the package. If you can test it in your existing apps then we can make sure I didn't break anything :)

**Comment by sbekrin** [comment]
@jimthedev thanks, I finally had some time to check you fork. The biggest issue I see is that `React.ComponentClass<any>` is killing information about prop types for output component. This breaks autocompletion for me on VS Code with TS v2.5.3.

I believe having separate types definition is best option to go, will add that soon.

**Comment by sbekrin** [comment]
Hey @jimthedev, just to let you know — typings issue should be fixed in major v4.0.1 release. Feel free to re-open this issue if something doesn't work for you.
