### ISSUE TITLE
win10 ie11 performance

### ISSUE THREAD

**Issue by Remownz** [sergeybekrin/react-with-async-fonts#27]
i used your hoc for several components, e.g headings, texts etc. All works fine in chrome, firefox safari, edge and ie11 (win7). With ie11 (win10) i had massive performance issues sometimes with full browser crash. I profiled and found heavy cpu usage for your load function:https://github.com/sergeybekrin/react-with-async-fonts/blob/20614b2229509783a1d76ff62216c518ea9fc32e/src/helpers.ts#L8
I think the heavy load is caused by lots of fontfaceobserver instances. I ended up by using withAsyncFont for my App component only and setting global classNames.
Maybe u could check and confirm this behavior?!

**Comment by sbekrin** [comment]
Hey @Remownz, thanks for sharing this!

If you want to keep components isolated I can suggest two options:
1. If you have state-management (e.g. Redux), keep information about resolved font in state and reuse it.
2. Use context to collect fonts information once and pass it down. This will require custom implementation.

This is a pretty good point of possible performance bottleneck, it could be context option will work quite well and can be integrated into module itself. Meanwhile you can stick to global class if that works for you.

**Comment by sbekrin** [comment]
@Remownz I've published new api with breaking changes as v4.0.1. It uses context which should solve your perf issues. Feel free to update this issue if you came up with something. Cheers ✌️
