### ISSUE TITLE
What does it do ?

### ISSUE THREAD

**Issue by melMass** [sergeybekrin/react-with-async-fonts#53]
Hi,

I'm using custom fonts for my website. For now, I use base64 string so that it forces the browser to load the font before displaying anything on the screen. It avoids the font flickering on load but I think this library might be a better suit. But I can't seem to find what it does? Sorry if that's obvious to some.

**Comment by sbekrin** [comment]
Hey @melMass, this module allows you to render text as early as possible with a system font until custom one is loaded. It sounds like a potential solution for your case, considering you're fine with swapping fonts on-fly.

You can achieve same behavior by loading font asynchronously and applying [`font-display: swap`](https://css-tricks.com/font-display-masses/) CSS rule for [browsers which supports it](https://caniuse.com/#search=font-display). If you're happy with results, you can integrate this module to support legacy browsers too.

Hope that helps!

**Comment by melMass** [comment]
Thanks for the reply. 
Sorry but I still don't grasp the use cases.
I think the issue is that not all browser does the same.
Firefox does render system font then custom once loaded (resulting in a visual `glitch/swap` which I'm trying to avoid.)

**Comment by sbekrin** [comment]
In that case you can stick to your current approach, but maybe make sure page is usable on a slow network. Cheers!
